name: Commit checks

on: [push]

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Restore packages cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          yarn install --frozen-lockfile --ignore-scripts
          rm .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        run: yarn test

      - uses: actions/upload-artifact@v3
        with:
          name: cypress-outputs
          path: |
            cypress/videos
            cypress/screenshots

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Restore packages cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          yarn install --frozen-lockfile --ignore-scripts
          rm .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run ESLint
        run: yarn lint
